# Generated by Django 2.0 on 2019-05-28 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20190528_1230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='read_nums',
            field=models.IntegerField(default=0),
        ),
    ]
