# Generated by Django 2.0 on 2019-06-03 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20190603_1027'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='good',
            field=models.IntegerField(default=0),
        ),
    ]
