# Generated by Django 2.0 on 2019-06-03 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_blog_good'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='good',
        ),
    ]
